apiVersion: apps/v1
kind: Deployment
metadata:
  name: ovrednotenje-izdelkov-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ovrednotenje-izdelkov
  template:
    metadata:
      labels:
        app: ovrednotenje-izdelkov
    spec:
      containers:
        - image: rsoskupina50/vrednotenje-izdelkov:2023-01-04-18-41-26
          name: ovrednotenje-izdelkov
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://snuffleupagus.db.elephantsql.com/daggxydk
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: daggxydk
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              value: 31ll2StFZDv6oXF5oB3QaZYFWzzMo1IG
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/live
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3

---

apiVersion: v1
kind: Service
metadata:
  name: ovrednotenje-izdelkov
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: ovrednotenje-izdelkov
